version: '2'

services:
  db:
    image: rethinkdb
  frontend:
    build: ./frontend
    image: frontend
    depends_on:
      - db
    ports:
      - '8000:8000'
    links:
      - db
    environment:
      - DATABASE_HOST=db
#      - 'DATABASE_PORT: 28015'