version: '2'

volumes:
  rethink-data:
    driver: local

services:
  db:
    image: rethinkdb
    depends_on:
      - logging
    volumes:
      - rethink-data:/data
    ports:
      - 28015:28015
      - 29015:29015
      - 8080:8080
  frontend:
    build: ./frontend
    image: frontend
    depends_on:
      - db
      - logging
    ports:
      - '8000:8000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=28015
  logging:
    build: ./logging 
    image: inventory-logging
    ports:
      - '514:514'
      - '601:601'
      - '6514:6514'
    environment:
      - ENVIRONMENT=development