version: '2'

volumes:
  rethink-data:
    driver: local

services:
  db:
    networks:
      - net
    image: rethinkdb
    volumes:
      - rethink-data:/data
    ports:
      - 28015
      - 29015
      - 8080
    command: rethinkdb --bind all --cache-size 2048
  frontend:
    networks:
      - net
    build: ./frontend
    image: frontend
    depends_on:
      - db
    ports:
      - '8000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=28015

networks:
  net:
    driver: bridge
